version: '3.1'

services:
  postgis:
    image: postgis/postgis:13-3.2
    ports:
      - ${LANGER_DB_PORT}:5432
    environment:
      POSTGRES_USER: ${LANGER_DB_USER}
      POSTGRES_PASSWORD: ${LANGER_DB_PASSWORD}
      POSTGRES_DB: ${LANGER_DB_NAME}
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${LANGER_DB_USER} -d ${LANGER_DB_NAME}" ]
      retries: 5
      timeout: 5s
      interval: 10s

